/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as CruiseExperienceRouteImport } from './routes/cruise-experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabinsRouteImport } from './routes/cabins'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffLoginRouteImport } from './routes/staff_.login'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffRoomsRouteImport } from './routes/staff.rooms'
import { Route as StaffRoomSettingsRouteImport } from './routes/staff.room-settings'
import { Route as StaffPackagesRouteImport } from './routes/staff.packages'
import { Route as StaffGalleryRouteImport } from './routes/staff.gallery'
import { Route as StaffFoodMenuRouteImport } from './routes/staff.food-menu'
import { Route as StaffCabinsRouteImport } from './routes/staff.cabins'
import { Route as StaffBookingsRouteImport } from './routes/staff.bookings'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailRouteImport } from './routes/payment.fail'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as CabinsSlugRouteImport } from './routes/cabins_.$slug'
import { Route as BookingConfirmationCodeRouteImport } from './routes/booking_.confirmation.$code'

const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseExperienceRoute = CruiseExperienceRouteImport.update({
  id: '/cruise-experience',
  path: '/cruise-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsRoute = CabinsRouteImport.update({
  id: '/cabins',
  path: '/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff_/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRoomsRoute = StaffRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRoomSettingsRoute = StaffRoomSettingsRouteImport.update({
  id: '/room-settings',
  path: '/room-settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPackagesRoute = StaffPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGalleryRoute = StaffGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFoodMenuRoute = StaffFoodMenuRouteImport.update({
  id: '/food-menu',
  path: '/food-menu',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCabinsRoute = StaffCabinsRouteImport.update({
  id: '/cabins',
  path: '/cabins',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailRoute = PaymentFailRouteImport.update({
  id: '/payment/fail',
  path: '/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsSlugRoute = CabinsSlugRouteImport.update({
  id: '/cabins_/$slug',
  path: '/cabins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationCodeRoute = BookingConfirmationCodeRouteImport.update({
  id: '/booking_/confirmation/$code',
  path: '/booking/confirmation/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/policy': typeof PolicyRoute
  '/staff': typeof StaffRouteWithChildren
  '/wildlife': typeof WildlifeRoute
  '/cabins/$slug': typeof CabinsSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/cabins': typeof StaffCabinsRoute
  '/staff/food-menu': typeof StaffFoodMenuRoute
  '/staff/gallery': typeof StaffGalleryRoute
  '/staff/packages': typeof StaffPackagesRoute
  '/staff/room-settings': typeof StaffRoomSettingsRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/': typeof StaffIndexRoute
  '/booking/confirmation/$code': typeof BookingConfirmationCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/policy': typeof PolicyRoute
  '/wildlife': typeof WildlifeRoute
  '/cabins/$slug': typeof CabinsSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/cabins': typeof StaffCabinsRoute
  '/staff/food-menu': typeof StaffFoodMenuRoute
  '/staff/gallery': typeof StaffGalleryRoute
  '/staff/packages': typeof StaffPackagesRoute
  '/staff/room-settings': typeof StaffRoomSettingsRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff': typeof StaffIndexRoute
  '/booking/confirmation/$code': typeof BookingConfirmationCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/policy': typeof PolicyRoute
  '/staff': typeof StaffRouteWithChildren
  '/wildlife': typeof WildlifeRoute
  '/cabins_/$slug': typeof CabinsSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/cabins': typeof StaffCabinsRoute
  '/staff/food-menu': typeof StaffFoodMenuRoute
  '/staff/gallery': typeof StaffGalleryRoute
  '/staff/packages': typeof StaffPackagesRoute
  '/staff/room-settings': typeof StaffRoomSettingsRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff_/login': typeof StaffLoginRoute
  '/staff/': typeof StaffIndexRoute
  '/booking_/confirmation/$code': typeof BookingConfirmationCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/policy'
    | '/staff'
    | '/wildlife'
    | '/cabins/$slug'
    | '/payment/cancel'
    | '/payment/fail'
    | '/payment/success'
    | '/staff/bookings'
    | '/staff/cabins'
    | '/staff/food-menu'
    | '/staff/gallery'
    | '/staff/packages'
    | '/staff/room-settings'
    | '/staff/rooms'
    | '/staff/settings'
    | '/staff/login'
    | '/staff/'
    | '/booking/confirmation/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/policy'
    | '/wildlife'
    | '/cabins/$slug'
    | '/payment/cancel'
    | '/payment/fail'
    | '/payment/success'
    | '/staff/bookings'
    | '/staff/cabins'
    | '/staff/food-menu'
    | '/staff/gallery'
    | '/staff/packages'
    | '/staff/room-settings'
    | '/staff/rooms'
    | '/staff/settings'
    | '/staff/login'
    | '/staff'
    | '/booking/confirmation/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/policy'
    | '/staff'
    | '/wildlife'
    | '/cabins_/$slug'
    | '/payment/cancel'
    | '/payment/fail'
    | '/payment/success'
    | '/staff/bookings'
    | '/staff/cabins'
    | '/staff/food-menu'
    | '/staff/gallery'
    | '/staff/packages'
    | '/staff/room-settings'
    | '/staff/rooms'
    | '/staff/settings'
    | '/staff_/login'
    | '/staff/'
    | '/booking_/confirmation/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CabinsRoute: typeof CabinsRoute
  ContactRoute: typeof ContactRoute
  CruiseExperienceRoute: typeof CruiseExperienceRoute
  DiningRoute: typeof DiningRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRoute
  PolicyRoute: typeof PolicyRoute
  StaffRoute: typeof StaffRouteWithChildren
  WildlifeRoute: typeof WildlifeRoute
  CabinsSlugRoute: typeof CabinsSlugRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentFailRoute: typeof PaymentFailRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  StaffLoginRoute: typeof StaffLoginRoute
  BookingConfirmationCodeRoute: typeof BookingConfirmationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise-experience': {
      id: '/cruise-experience'
      path: '/cruise-experience'
      fullPath: '/cruise-experience'
      preLoaderRoute: typeof CruiseExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins': {
      id: '/cabins'
      path: '/cabins'
      fullPath: '/cabins'
      preLoaderRoute: typeof CabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff_/login': {
      id: '/staff_/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/rooms': {
      id: '/staff/rooms'
      path: '/rooms'
      fullPath: '/staff/rooms'
      preLoaderRoute: typeof StaffRoomsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/room-settings': {
      id: '/staff/room-settings'
      path: '/room-settings'
      fullPath: '/staff/room-settings'
      preLoaderRoute: typeof StaffRoomSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/packages': {
      id: '/staff/packages'
      path: '/packages'
      fullPath: '/staff/packages'
      preLoaderRoute: typeof StaffPackagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/gallery': {
      id: '/staff/gallery'
      path: '/gallery'
      fullPath: '/staff/gallery'
      preLoaderRoute: typeof StaffGalleryRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/food-menu': {
      id: '/staff/food-menu'
      path: '/food-menu'
      fullPath: '/staff/food-menu'
      preLoaderRoute: typeof StaffFoodMenuRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/cabins': {
      id: '/staff/cabins'
      path: '/cabins'
      fullPath: '/staff/cabins'
      preLoaderRoute: typeof StaffCabinsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/fail': {
      id: '/payment/fail'
      path: '/payment/fail'
      fullPath: '/payment/fail'
      preLoaderRoute: typeof PaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins_/$slug': {
      id: '/cabins_/$slug'
      path: '/cabins/$slug'
      fullPath: '/cabins/$slug'
      preLoaderRoute: typeof CabinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_/confirmation/$code': {
      id: '/booking_/confirmation/$code'
      path: '/booking/confirmation/$code'
      fullPath: '/booking/confirmation/$code'
      preLoaderRoute: typeof BookingConfirmationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StaffRouteChildren {
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffCabinsRoute: typeof StaffCabinsRoute
  StaffFoodMenuRoute: typeof StaffFoodMenuRoute
  StaffGalleryRoute: typeof StaffGalleryRoute
  StaffPackagesRoute: typeof StaffPackagesRoute
  StaffRoomSettingsRoute: typeof StaffRoomSettingsRoute
  StaffRoomsRoute: typeof StaffRoomsRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBookingsRoute: StaffBookingsRoute,
  StaffCabinsRoute: StaffCabinsRoute,
  StaffFoodMenuRoute: StaffFoodMenuRoute,
  StaffGalleryRoute: StaffGalleryRoute,
  StaffPackagesRoute: StaffPackagesRoute,
  StaffRoomSettingsRoute: StaffRoomSettingsRoute,
  StaffRoomsRoute: StaffRoomsRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CabinsRoute: CabinsRoute,
  ContactRoute: ContactRoute,
  CruiseExperienceRoute: CruiseExperienceRoute,
  DiningRoute: DiningRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRoute,
  PolicyRoute: PolicyRoute,
  StaffRoute: StaffRouteWithChildren,
  WildlifeRoute: WildlifeRoute,
  CabinsSlugRoute: CabinsSlugRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentFailRoute: PaymentFailRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  StaffLoginRoute: StaffLoginRoute,
  BookingConfirmationCodeRoute: BookingConfirmationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
